---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3359308690-FyuYcZgYpmEKe1CwT96XUmL6zxeGQwEuqVvefZZ
:access_token_secret: iPYe3k6iTndXiVAw1xKujP2GfNZIrNm30tVe9zICP8M49
